/*
 * This source file was generated by the Gradle 'init' task
 */
package demo;
import java.util.Collection;
import java.util.HashSet;

import tb.simple.api.TbSimple.IVoidInterface;
import tb.simple.api.TbSimple.IVoidInterfaceEventListener;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static class EventLister implements IVoidInterfaceEventListener {
        @Override
        public void onSigVoid() {
            System.out.println("onSigVoid");
        }
    }

    public static class Demo implements IVoidInterface {
        public Collection<IVoidInterfaceEventListener> listeners = new HashSet<>();

        @Override
        public void funcVoid() {
            System.out.println("funcVoid");
        }

        public void addEventListener(IVoidInterfaceEventListener listener) {
            System.out.println("addEventListener");
            listeners.add(listener); 
        }
        public void removeEventListener(IVoidInterfaceEventListener listener) {
            System.out.println("removeEventListener");
            listeners.remove(listener);
        }
        public void fireSigVoid() {
            listeners.forEach(listener -> listener.onSigVoid());
        }
    }


    public static void main(String[] args) {
        Demo demo = new Demo();
        demo.addEventListener(new EventLister());
        demo.funcVoid();
        System.out.println(new App().getGreeting());
    }
}
