android {
    namespace 'tbSame1.tbSame1_android_service'

	tasks.register('packageSources', Jar) {
		archiveClassifier.set('sources')
		from android.sourceSets.main.java.srcDirs
		include '**/*.java'
	}
}

dependencies {
	implementation 'androidx.appcompat:appcompat:1.2.0'
    implementation project(':tbSame1_api')
    api project(':tbSame1_impl')
    api project(':tbSame1_android_messenger')
    testImplementation 'junit:junit:4.13.2'
    testImplementation 'org.robolectric:robolectric:4.10.3'
    testImplementation 'org.mockito:mockito-core:5.12.0'
    testImplementation 'org.mockito:mockito-inline:5.2.0'
}
