pluginManagement {
    repositories {
        google {
            content {
                includeGroupByRegex("com\\.android.*")
                includeGroupByRegex("com\\.google.*")
                includeGroupByRegex("androidx.*")
            }
        }
        mavenCentral()
        gradlePluginPortal()
    }
}
dependencyResolutionManagement {
    repositoriesMode.set(RepositoriesMode.FAIL_ON_PROJECT_REPOS)
    repositories {
        google()
        mavenCentral()
    }
}

rootProject.name = "testbed1"
include ':testbed1_android_service'
include ':testbed1_android_client'
include ':testbed1_android_messenger'
include ':testbed1_impl'
include ':testbed1_api'
include ':testbed1_client_example'
include ':testbed1serviceexample'