plugins {
    alias(libs.plugins.android.application)
}

group = "testbed2"
version = "1.0.0"


android {
    namespace 'testbed2.testbed2serviceexample'
    compileSdk 35

    defaultConfig {
        applicationId "testbed2.testbed2serviceexample"
        minSdk 33
        targetSdk 35
        versionCode 1
        versionName "1.0"

        testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"
    }

    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_11
        targetCompatibility JavaVersion.VERSION_11
    }
}

dependencies {

    implementation libs.appcompat
    implementation libs.material
    implementation project(':testbed2_api')
    implementation project(':testbed2_android_messenger')
    implementation project(':testbed2_android_service')
    implementation project(':testbed2_impl')
    testImplementation libs.junit
    androidTestImplementation libs.ext.junit
    androidTestImplementation libs.espresso.core
}