plugins {
    id 'java-library'
}

group = "counter"
version = "1.0.0"

java {
    sourceCompatibility = JavaVersion.VERSION_11
    targetCompatibility = JavaVersion.VERSION_11
}

dependencies {
    implementation 'com.fasterxml.jackson.core:jackson-annotations:2.17.0'
    api 'customTypes:customTypes_api:1.0.0'
    api 'externTypes:externTypes_api:1.0.0'
}