plugins {
    alias(libs.plugins.android.application)
}

group = "tbSame1"
version = "1.0.0"

android {
    namespace 'tbSame1.tbSame1_client_example'
    compileSdk 35

    defaultConfig {
        applicationId "tbSame1.tbSame1_client_example"
        minSdk 33
        targetSdk 35
        versionCode 1
        versionName "1.0"

        testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"
    }

    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_11
        targetCompatibility JavaVersion.VERSION_11
    }
}

dependencies {

    implementation libs.appcompat
    implementation libs.material
    implementation project(':tbSame1_api')
    implementation project(':tbSame1_android_messenger')
    implementation project(':tbSame1_android_client')
    testImplementation libs.junit
    androidTestImplementation libs.ext.junit
    androidTestImplementation libs.espresso.core
}