pluginManagement {
    repositories {
        google {
            content {
                includeGroupByRegex("com\\.android.*")
                includeGroupByRegex("com\\.google.*")
                includeGroupByRegex("androidx.*")
            }
        }
        mavenCentral()
        gradlePluginPortal()
    }
}
dependencyResolutionManagement {
    repositoriesMode.set(RepositoriesMode.FAIL_ON_PROJECT_REPOS)
    repositories {
        google()
        mavenCentral()
    }
}

rootProject.name = "customTypes"
include ':customTypes_android_service'
include ':customTypes_android_client'
include ':customTypes_android_messenger'
include ':customTypes_impl'
include ':customTypes_api'
include ':customTypes_client_example'
include ':customTypesserviceexample'